### ISSUE TITLE
Error: module "network": "allow_ssh_traffic" is not a valid argument

### ISSUE THREAD

**Issue by jdneo** [Azure/terraform-azurerm-compute#53]
I got this error when I run the e2e test by the docker image: `microsoft/terraform-test`

kitchen.log:
```
I, [2018-02-03T05:25:11.586708 #6]  INFO -- Kitchen: -----> Starting Kitchen (v1.16.0)
W, [2018-02-03T05:25:11.846949 #6]  WARN -- Kitchen: Running command `terraform version`
I, [2018-02-03T05:25:11.875759 #6]  INFO -- Kitchen: Terraform v0.11.3
I, [2018-02-03T05:25:11.887853 #6]  INFO -- Kitchen: 
W, [2018-02-03T05:25:13.236569 #6]  WARN -- Kitchen: Terraform v0.11.3 is supported
I, [2018-02-03T05:25:14.246586 #6]  INFO -- Kitchen: -----> Cleaning up any prior instances of <compute-ubuntu>
I, [2018-02-03T05:25:14.254272 #6]  INFO -- Kitchen: -----> Destroying <compute-ubuntu>...
E, [2018-02-03T05:25:18.644576 #6] ERROR -- Kitchen: ------Exception-------
E, [2018-02-03T05:25:18.645129 #6] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2018-02-03T05:25:18.645582 #6] ERROR -- Kitchen: Message: 1 actions failed.
>>>>>>     Destroy failed on instance <compute-ubuntu>.  Please see .kitchen/logs/compute-ubuntu.log for more details
E, [2018-02-03T05:25:18.646032 #6] ERROR -- Kitchen: ----------------------
E, [2018-02-03T05:25:18.646388 #6] ERROR -- Kitchen: ------Backtrace-------
E, [2018-02-03T05:25:18.646750 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:183:in `report_errors'
E, [2018-02-03T05:25:18.647120 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:174:in `run_action'
E, [2018-02-03T05:25:18.647465 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/command/test.rb:42:in `block in call'
E, [2018-02-03T05:25:18.647797 #6] ERROR -- Kitchen: /usr/local/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2018-02-03T05:25:18.648129 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/command/test.rb:38:in `call'
E, [2018-02-03T05:25:18.648452 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:53:in `perform'
E, [2018-02-03T05:25:18.648885 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:234:in `test'
E, [2018-02-03T05:25:18.649235 #6] ERROR -- Kitchen: /usr/local/bundle/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
E, [2018-02-03T05:25:18.649556 #6] ERROR -- Kitchen: /usr/local/bundle/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
E, [2018-02-03T05:25:18.649865 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:334:in `invoke_task'
E, [2018-02-03T05:25:18.650183 #6] ERROR -- Kitchen: /usr/local/bundle/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
E, [2018-02-03T05:25:18.650491 #6] ERROR -- Kitchen: /usr/local/bundle/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
E, [2018-02-03T05:25:18.650779 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/bin/kitchen:13:in `block in <top (required)>'
E, [2018-02-03T05:25:18.651160 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/errors.rb:171:in `with_friendly_errors'
E, [2018-02-03T05:25:18.651454 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/bin/kitchen:13:in `<top (required)>'
E, [2018-02-03T05:25:18.651733 #6] ERROR -- Kitchen: /usr/local/bundle/bin/kitchen:23:in `load'
E, [2018-02-03T05:25:18.651988 #6] ERROR -- Kitchen: /usr/local/bundle/bin/kitchen:23:in `<main>'
E, [2018-02-03T05:25:18.652258 #6] ERROR -- Kitchen: ----End Backtrace-----
E, [2018-02-03T05:25:18.652538 #6] ERROR -- Kitchen: -Composite Exception--
E, [2018-02-03T05:25:18.652827 #6] ERROR -- Kitchen: Class: Kitchen::InstanceFailure
E, [2018-02-03T05:25:18.653091 #6] ERROR -- Kitchen: Message: Destroy failed on instance <compute-ubuntu>.  Please see .kitchen/logs/compute-ubuntu.log for more details
E, [2018-02-03T05:25:18.653359 #6] ERROR -- Kitchen: ----------------------
E, [2018-02-03T05:25:18.653652 #6] ERROR -- Kitchen: ------Backtrace-------
E, [2018-02-03T05:25:18.653971 #6] ERROR -- Kitchen: /usr/local/bundle/gems/kitchen-terraform-3.0.0/lib/kitchen/driver/terraform.rb:264:in `block in destroy'
E, [2018-02-03T05:25:18.654237 #6] ERROR -- Kitchen: /usr/local/bundle/gems/dry-monads-0.4.0/lib/dry/monads/result.rb:159:in `or'
E, [2018-02-03T05:25:18.654517 #6] ERROR -- Kitchen: /usr/local/bundle/gems/kitchen-terraform-3.0.0/lib/kitchen/driver/terraform.rb:263:in `destroy'
E, [2018-02-03T05:25:18.654765 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `public_send'
E, [2018-02-03T05:25:18.655018 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `block in perform_action'
E, [2018-02-03T05:25:18.655267 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
E, [2018-02-03T05:25:18.655510 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:489:in `block in action'
E, [2018-02-03T05:25:18.655732 #6] ERROR -- Kitchen: /usr/local/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2018-02-03T05:25:18.656021 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:488:in `action'
E, [2018-02-03T05:25:18.656352 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `perform_action'
E, [2018-02-03T05:25:18.656659 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:447:in `destroy_action'
E, [2018-02-03T05:25:18.656941 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:359:in `block in transition_to'
E, [2018-02-03T05:25:18.657212 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `each'
E, [2018-02-03T05:25:18.657466 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `transition_to'
E, [2018-02-03T05:25:18.657755 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:168:in `destroy'
E, [2018-02-03T05:25:18.658053 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:184:in `block in test'
E, [2018-02-03T05:25:18.658307 #6] ERROR -- Kitchen: /usr/local/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2018-02-03T05:25:18.658560 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:182:in `test'
E, [2018-02-03T05:25:18.658804 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `public_send'
E, [2018-02-03T05:25:18.659055 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2018-02-03T05:25:18.659308 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2018-02-03T05:25:18.659528 #6] ERROR -- Kitchen: ----End Backtrace-----
E, [2018-02-03T05:25:18.659798 #6] ERROR -- Kitchen: ---Nested Exception---
E, [2018-02-03T05:25:18.660092 #6] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2018-02-03T05:25:18.660414 #6] ERROR -- Kitchen: Message: Running command resulted in failure: Expected process to exit with [0], but received '1'
---- Begin output of terraform init -input=false -lock=true -lock-timeout=0s -no-color -force-copy -backend=true  -get=true -get-plugins=true  -verify-plugins=true /tf-test/module/test/integration/fixtures ----
STDOUT: Initializing modules...
- module.linuxservers
- module.network
  Found version 2.0.0 of Azure/network/azurerm on registry.terraform.io
  Getting source "Azure/network/azurerm"
- module.linuxservers.os
  Getting source "./os"
STDERR: Error: module "network": "allow_ssh_traffic" is not a valid argument
---- End output of terraform init -input=false -lock=true -lock-timeout=0s -no-color -force-copy -backend=true  -get=true -get-plugins=true  -verify-plugins=true /tf-test/module/test/integration/fixtures ----
Ran terraform init -input=false -lock=true -lock-timeout=0s -no-color -force-copy -backend=true  -get=true -get-plugins=true  -verify-plugins=true /tf-test/module/test/integration/fixtures returned 1
E, [2018-02-03T05:25:18.660678 #6] ERROR -- Kitchen: ----------------------
E, [2018-02-03T05:25:18.660932 #6] ERROR -- Kitchen: ------Backtrace-------
E, [2018-02-03T05:25:18.661229 #6] ERROR -- Kitchen: /usr/local/bundle/gems/kitchen-terraform-3.0.0/lib/kitchen/driver/terraform.rb:264:in `block in destroy'
E, [2018-02-03T05:25:18.661456 #6] ERROR -- Kitchen: /usr/local/bundle/gems/dry-monads-0.4.0/lib/dry/monads/result.rb:159:in `or'
E, [2018-02-03T05:25:18.661719 #6] ERROR -- Kitchen: /usr/local/bundle/gems/kitchen-terraform-3.0.0/lib/kitchen/driver/terraform.rb:263:in `destroy'
E, [2018-02-03T05:25:18.662040 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `public_send'
E, [2018-02-03T05:25:18.662390 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `block in perform_action'
E, [2018-02-03T05:25:18.662664 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
E, [2018-02-03T05:25:18.662918 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:489:in `block in action'
E, [2018-02-03T05:25:18.663190 #6] ERROR -- Kitchen: /usr/local/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2018-02-03T05:25:18.663464 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:488:in `action'
E, [2018-02-03T05:25:18.663805 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `perform_action'
E, [2018-02-03T05:25:18.664120 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:447:in `destroy_action'
E, [2018-02-03T05:25:18.664430 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:359:in `block in transition_to'
E, [2018-02-03T05:25:18.664719 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `each'
E, [2018-02-03T05:25:18.665039 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `transition_to'
E, [2018-02-03T05:25:18.665308 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:168:in `destroy'
E, [2018-02-03T05:25:18.665615 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:184:in `block in test'
E, [2018-02-03T05:25:18.665911 #6] ERROR -- Kitchen: /usr/local/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2018-02-03T05:25:18.666162 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:182:in `test'
E, [2018-02-03T05:25:18.666419 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `public_send'
E, [2018-02-03T05:25:18.666696 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2018-02-03T05:25:18.666988 #6] ERROR -- Kitchen: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2018-02-03T05:25:18.667245 #6] ERROR -- Kitchen: ----End Backtrace-----
```

compute-ubuntu.log:
```
I, [2018-02-03T05:25:14.247044 #6]  INFO -- compute-ubuntu: -----> Cleaning up any prior instances of <compute-ubuntu>
I, [2018-02-03T05:25:14.254714 #6]  INFO -- compute-ubuntu: -----> Destroying <compute-ubuntu>...
W, [2018-02-03T05:25:14.258505 #6]  WARN -- compute-ubuntu: Running command `terraform init -input=false -lock=true -lock-timeout=0s -no-color -force-copy -backend=true  -get=true -get-plugins=true  -verify-plugins=true /tf-test/module/test/integration/fixtures`
I, [2018-02-03T05:25:14.301039 #6]  INFO -- compute-ubuntu: Initializing modules...
I, [2018-02-03T05:25:14.310864 #6]  INFO -- compute-ubuntu: - module.linuxservers
I, [2018-02-03T05:25:14.341913 #6]  INFO -- compute-ubuntu: - module.network
I, [2018-02-03T05:25:16.292903 #6]  INFO -- compute-ubuntu:   Found version 2.0.0 of Azure/network/azurerm on registry.terraform.io
I, [2018-02-03T05:25:16.296102 #6]  INFO -- compute-ubuntu:   Getting source "Azure/network/azurerm"
I, [2018-02-03T05:25:18.507559 #6]  INFO -- compute-ubuntu: - module.linuxservers.os
I, [2018-02-03T05:25:18.511741 #6]  INFO -- compute-ubuntu:   Getting source "./os"
I, [2018-02-03T05:25:18.626512 #6]  INFO -- compute-ubuntu: 
I, [2018-02-03T05:25:18.629023 #6]  INFO -- compute-ubuntu: Error: module "network": "allow_ssh_traffic" is not a valid argument
I, [2018-02-03T05:25:18.629489 #6]  INFO -- compute-ubuntu: 
I, [2018-02-03T05:25:18.630378 #6]  INFO -- compute-ubuntu: 
E, [2018-02-03T05:25:18.631463 #6] ERROR -- compute-ubuntu: Destroy failed on instance <compute-ubuntu>.
E, [2018-02-03T05:25:18.632053 #6] ERROR -- compute-ubuntu: ------Exception-------
E, [2018-02-03T05:25:18.632564 #6] ERROR -- compute-ubuntu: Class: Kitchen::ActionFailed
E, [2018-02-03T05:25:18.632958 #6] ERROR -- compute-ubuntu: Message: Running command resulted in failure: Expected process to exit with [0], but received '1'
---- Begin output of terraform init -input=false -lock=true -lock-timeout=0s -no-color -force-copy -backend=true  -get=true -get-plugins=true  -verify-plugins=true /tf-test/module/test/integration/fixtures ----
STDOUT: Initializing modules...
- module.linuxservers
- module.network
  Found version 2.0.0 of Azure/network/azurerm on registry.terraform.io
  Getting source "Azure/network/azurerm"
- module.linuxservers.os
  Getting source "./os"
STDERR: Error: module "network": "allow_ssh_traffic" is not a valid argument
---- End output of terraform init -input=false -lock=true -lock-timeout=0s -no-color -force-copy -backend=true  -get=true -get-plugins=true  -verify-plugins=true /tf-test/module/test/integration/fixtures ----
Ran terraform init -input=false -lock=true -lock-timeout=0s -no-color -force-copy -backend=true  -get=true -get-plugins=true  -verify-plugins=true /tf-test/module/test/integration/fixtures returned 1
E, [2018-02-03T05:25:18.633367 #6] ERROR -- compute-ubuntu: ----------------------
E, [2018-02-03T05:25:18.633691 #6] ERROR -- compute-ubuntu: ------Backtrace-------
E, [2018-02-03T05:25:18.634003 #6] ERROR -- compute-ubuntu: /usr/local/bundle/gems/kitchen-terraform-3.0.0/lib/kitchen/driver/terraform.rb:264:in `block in destroy'
E, [2018-02-03T05:25:18.634394 #6] ERROR -- compute-ubuntu: /usr/local/bundle/gems/dry-monads-0.4.0/lib/dry/monads/result.rb:159:in `or'
E, [2018-02-03T05:25:18.634729 #6] ERROR -- compute-ubuntu: /usr/local/bundle/gems/kitchen-terraform-3.0.0/lib/kitchen/driver/terraform.rb:263:in `destroy'
E, [2018-02-03T05:25:18.635096 #6] ERROR -- compute-ubuntu: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `public_send'
E, [2018-02-03T05:25:18.635437 #6] ERROR -- compute-ubuntu: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `block in perform_action'
E, [2018-02-03T05:25:18.635779 #6] ERROR -- compute-ubuntu: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
E, [2018-02-03T05:25:18.636099 #6] ERROR -- compute-ubuntu: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:489:in `block in action'
E, [2018-02-03T05:25:18.636375 #6] ERROR -- compute-ubuntu: /usr/local/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2018-02-03T05:25:18.636762 #6] ERROR -- compute-ubuntu: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:488:in `action'
E, [2018-02-03T05:25:18.637093 #6] ERROR -- compute-ubuntu: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `perform_action'
E, [2018-02-03T05:25:18.637426 #6] ERROR -- compute-ubuntu: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:447:in `destroy_action'
E, [2018-02-03T05:25:18.637719 #6] ERROR -- compute-ubuntu: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:359:in `block in transition_to'
E, [2018-02-03T05:25:18.638013 #6] ERROR -- compute-ubuntu: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `each'
E, [2018-02-03T05:25:18.638341 #6] ERROR -- compute-ubuntu: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `transition_to'
E, [2018-02-03T05:25:18.638669 #6] ERROR -- compute-ubuntu: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:168:in `destroy'
E, [2018-02-03T05:25:18.638979 #6] ERROR -- compute-ubuntu: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:184:in `block in test'
E, [2018-02-03T05:25:18.639248 #6] ERROR -- compute-ubuntu: /usr/local/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2018-02-03T05:25:18.639530 #6] ERROR -- compute-ubuntu: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:182:in `test'
E, [2018-02-03T05:25:18.639850 #6] ERROR -- compute-ubuntu: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `public_send'
E, [2018-02-03T05:25:18.640127 #6] ERROR -- compute-ubuntu: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2018-02-03T05:25:18.640419 #6] ERROR -- compute-ubuntu: /usr/local/bundle/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2018-02-03T05:25:18.640673 #6] ERROR -- compute-ubuntu: ----End Backtrace-----
```

**Comment by dcaro** [comment]
This is fixed with the merge of PR #52.

**Comment by metacpp** [comment]
This is a breaking change from 2.0.0 for network module.

**Comment by ctippur** [comment]
Is this error similar to https://github.com/hashicorp/terraform/issues/17665 ?
